/**
 * judge.js — Tier 3 cross-family judge: orchestration + public surface.
 *
 * The code under review is generated by Claude (Anthropic). To avoid a model
 * grading its own family's output, the judge MUST be a different family. This
 * is a load-bearing safety rule: Felix refuses to run with an Anthropic judge.
 *
 * Two judge families are implemented via plain REST (no SDK dependency): OpenAI
 * (default) and Google Gemini — a genuinely different vendor, which is the whole
 * point of a cross-family second opinion (R2b). Select with FELIX_JUDGE_FAMILY.
 * The judge reads the spec criteria + diff + Tier 1 outputs and rules each
 * criterion met/unmet with a short reason.
 *
 * This file now ORCHESTRATES a judge run — seat selection, budget planning, the
 * bounded retry, multi-chunk pacing, and the jury fan-out — and RE-EXPORTS the
 * public surface. The pieces it drives live in three modules (no cycles):
 *   ./prompt    — buildPrompt (the exact prompt string matrix). Reads ./budget and
 *                 ./providers for the untrusted-region caps; both are leaves, so the
 *                 graph stays acyclic.
 *   ./providers — PROVIDERS registry + httpError (the vendor REST contracts). A leaf.
 *   ./merge     — chunk/jury merges + coverage description. A leaf.
 */

const { logger } = require('./util/logger');
const { estimateTokens, planJudgeCalls, paceMs, promptBudgetTokens, DEFAULT_MAX_CHUNKS } = require('./budget');
const { buildPrompt } = require('./prompt');
const { PROVIDERS } = require('./providers');
const {
  alignSingleRulings, mergeChunkRulings, mergeJuryResults, chunkVerdict, describeCoverage,
} = require('./merge');

const ANTHROPIC_HINTS = [/anthropic/i, /\bclaude\b/i];

// A judge call that 429s on a RATE limit is worth retrying — the quota refills on a timer.
// Bounded, because a PR check that retries forever is worse than one that reports
// INSUFFICIENT EVIDENCE.
const MAX_RATE_LIMIT_RETRIES = 2;
const RETRY_BASE_MS = 20_000;

// …but OpenAI also returns 429 for a request that is too large for the per-minute budget
// FULL STOP ("Request too large for gpt-4.1 … TPM: Limit 30000, Requested 61227"). Waiting
// cannot help: the quota refills to a ceiling the request still exceeds. Retrying that is a
// guaranteed 60-second detour to the same failure, so it is thrown immediately. The budget
// planner should stop us from ever sending one; this is the belt to that suspenders.
const TOO_LARGE = /too large/i;

// Transient server-side failures deserve the same treatment as a rate limit: the vendor is
// telling us to come back, not that the request is wrong. Gemini in particular answers 503
// "This model is currently experiencing high demand … usually temporary" under load, and a
// seat that gives up on the first one silently DEGRADES the jury to a single vendor — which
// is the exact failure mode the two-vendor jury exists to prevent. Observed twice in one day
// on gemini-3.6-flash, both times knocking the jury down to openai-only.
const TRANSIENT_STATUSES = new Set([500, 502, 503, 504]);

const sleep = (ms) => (ms > 0 ? new Promise((r) => setTimeout(r, ms)) : Promise.resolve());

/** Throws if the configured judge is the same family as the code generator. */
function assertCrossFamily(family, model) {
  const f = String(family || '').toLowerCase();
  const m = String(model || '');
  if (f === 'anthropic' || ANTHROPIC_HINTS.some((re) => re.test(f) || re.test(m))) {
    throw new Error(
      `Cross-family integrity violation: judge family/model "${family}/${model}" is Anthropic. ` +
      'Felix refuses to let the code generator grade its own output. Set FELIX_JUDGE_FAMILY/MODEL to a different family (e.g. openai/gpt-4.1).'
    );
  }
}

/** Split a comma-separated env list into trimmed, non-empty entries. */
function parseList(value, { lower = false } = {}) {
  return String(value || '')
    .split(',')
    .map((s) => (lower ? s.trim().toLowerCase() : s.trim()))
    .filter(Boolean);
}

/**
 * @param {object} env
 * @param {{adversarial?: boolean, fetchImpl?: Function}} opts
 *   adversarial=true uses the refute-first prompt (R2a). fetchImpl injects a fetch for
 *   offline tests (defaults to the global fetch).
 *
 * FELIX_JUDGE_FAMILY accepts ONE family ("gemini") or a comma-separated JURY
 * ("openai,gemini"). A jury runs every seated vendor in parallel and merges by unanimity,
 * so two independent vendors must both agree before a criterion counts as met — which is
 * what kills single-model flukes. Duplicate families collapse: the same vendor voting
 * twice is not an independent second opinion.
 *
 * @returns judge fn, or null if NO seated family has an API key (judge skipped →
 *   INSUFFICIENT EVIDENCE).
 */
function createJudge(env = process.env, { adversarial = false, fetchImpl, sleepImpl } = {}) {
  const doFetch = fetchImpl || fetch;
  // Injectable so the offline suite can exercise pacing and retry logic without actually
  // waiting out a rate-limit window.
  const doSleep = sleepImpl || sleep;
  // Escape hatch for a repo whose PRs are routinely enormous and who would rather spend the
  // CI minutes than accept partial coverage.
  const maxChunks = Number(env.FELIX_JUDGE_MAX_CHUNKS) > 0
    ? Number(env.FELIX_JUDGE_MAX_CHUNKS)
    : DEFAULT_MAX_CHUNKS;
  const requested = parseList(env.FELIX_JUDGE_FAMILY || 'openai', { lower: true });
  const families = [...new Set(requested.length ? requested : ['openai'])];
  const models = parseList(env.FELIX_JUDGE_MODEL);

  // A single model override cannot describe a multi-vendor jury (a gpt-* id is meaningless
  // to Gemini). Demand one model per family, or none at all — never guess a mapping.
  if (models.length > 1 && models.length !== families.length) {
    throw new Error(
      `FELIX_JUDGE_MODEL lists ${models.length} model(s) but FELIX_JUDGE_FAMILY seats ${families.length} judge(s). ` +
      "Provide one model per family in the same order, or leave it unset to use each family's default."
    );
  }
  if (models.length === 1 && families.length > 1) {
    throw new Error(
      `FELIX_JUDGE_MODEL="${models[0]}" is ambiguous for a ${families.length}-vendor jury. ` +
      "Provide one model per family in the same order, or leave it unset to use each family's default."
    );
  }

  const budgetOverride = Number(env.FELIX_JUDGE_MAX_PROMPT_TOKENS) > 0
    ? Number(env.FELIX_JUDGE_MAX_PROMPT_TOKENS)
    : null;

  // The budget the UNTRUSTED prompt regions are sized against — one value for every seat, not
  // each seat's own. A jury only means something if its vendors graded the same evidence, so a
  // 200K-token Gemini seat must not be shown more of a PR's Tier 1 output than the 30K OpenAI
  // seat sitting beside it. Same value index.js caps the criteria with, so the two agree.
  const regionBudgetTokens = promptBudgetTokens(env, PROVIDERS);

  const seats = families.map((family, i) => {
    const rawProvider = PROVIDERS[family];
    const model = models[i] || (rawProvider && rawProvider.defaultModel) || '';
    // Load-bearing safety guard, applied PER SEAT: the code under review is Claude's, so
    // every judge must be a different family. Runs before the "known family?" check so a
    // misconfigured Anthropic judge always fails with the integrity error.
    assertCrossFamily(family, model);
    if (!rawProvider) {
      throw new Error(
        `FELIX_JUDGE_FAMILY="${family}" is not supported. Available families: ${Object.keys(PROVIDERS).join(', ')}.`
      );
    }
    // A repo on a higher (or lower) rate-limit tier can override the per-seat budget rather
    // than editing the registry. Applies to every seat: it describes THIS ACCOUNT's ceiling,
    // which is a property of the billing plan, not of the vendor.
    const provider = budgetOverride
      ? { ...rawProvider, maxPromptTokens: budgetOverride, tpm: budgetOverride }
      : rawProvider;
    return { family, provider, model };
  });

  const active = [];
  for (const seat of seats) {
    const apiKey = env[seat.provider.apiKeyEnv];
    if (!apiKey) {
      logger.warn(`${seat.provider.apiKeyEnv} not set — ${seat.family} judge seat skipped.`);
      continue;
    }
    active.push({ ...seat, apiKey });
  }
  if (!active.length) return null;

  // The bench, as BUILT — what any caller that names the grader must cite.
  //
  // FELIX_JUDGE_FAMILY names the seats REQUESTED. A vendor with no key is skipped a few lines
  // above with a warning, so the env string and the seats that actually voted can differ, and
  // they differ in the one direction that flatters a result: a solo run reported as a 2-vendor
  // jury overstates the grader, which makes any bound measured against it look stronger than it
  // is. That happened — a variance run declared `openai,gemini` with no GEMINI_API_KEY and the
  // report printed "measured against a 2-vendor JURY". `requested` and `skipped` are kept
  // alongside `active` on purpose: the mismatch is the interesting part, and a shape that can
  // only say who graded cannot show that a seat went missing.
  const bench = Object.freeze({
    requested: Object.freeze([...families]),
    active: Object.freeze(active.map((s) => Object.freeze({ family: s.family, model: s.model }))),
    skipped: Object.freeze(seats
      .filter((s) => !active.some((a) => a.family === s.family))
      .map((s) => Object.freeze({ family: s.family, reason: `${s.provider.apiKeyEnv} not set` }))),
  });
  // Non-writable so a caller cannot relabel the bench it was handed — the whole point is that
  // the grader's identity comes from construction, not from whatever the caller believes.
  const withBench = (fn) => Object.defineProperty(fn, 'seats', { value: bench, enumerable: true });

  // One call, with a bounded retry when the vendor says "come back later" rather than "your
  // request is wrong". Rate limits and transient 5xx both clear on their own; everything
  // else — a bad key, a safety block, an over-sized request — is final and fails fast.
  //
  // CROSS-SEAM CONTRACT: this closure reads the error shape built by providers.js `httpError`
  // — `e.status` (numeric HTTP status) drives the 429/TRANSIENT_STATUSES retry decision, and
  // `e.retryAfterMs` (optional) overrides the exponential backoff. TOO_LARGE.test(e.message)
  // runs against the `"Judge call failed: <status> …"` message to separate a refillable 429
  // from an oversized one that waiting can never fix. Kept a closure ON PURPOSE: it closes
  // over doFetch, doSleep and the per-seat apiKey/model — do not hoist it to module scope.
  const callOnce = async (seat, prompt) => {
    for (let attempt = 0; ; attempt++) {
      try {
        return await seat.provider.call({ apiKey: seat.apiKey, model: seat.model, prompt, fetch: doFetch });
      } catch (e) {
        // A 429 clears when the quota refills; a 5xx clears when the vendor recovers. Both are
        // worth waiting on. "Request too large" is neither — see TOO_LARGE.
        const rateLimited = e.status === 429 && !TOO_LARGE.test(e.message);
        const retryable = rateLimited || TRANSIENT_STATUSES.has(e.status);
        if (!retryable || attempt >= MAX_RATE_LIMIT_RETRIES) throw e;
        const waitMs = e.retryAfterMs || RETRY_BASE_MS * (attempt + 1);
        logger.warn(`${seat.family} judge rate-limited — retrying in ${Math.round(waitMs / 1000)}s (attempt ${attempt + 1}/${MAX_RATE_LIMIT_RETRIES}).`);
        await doSleep(waitMs);
      }
    }
  };

  const parseSeatResponse = (raw) => {
    try {
      return JSON.parse(raw);
    } catch (e) {
      throw new Error(`Judge returned non-JSON: ${e.message}`);
    }
  };

  const runSeat = async (seat, input) => {
    // Budget the WHOLE prompt, not just the diff. The original bug sized a 240 KB diff cap
    // against a 60K-token estimate and ignored the instructions, criteria and Tier 1 output
    // riding along with it — the live 429 billed 61,227 tokens for a request the cap thought
    // was exactly at budget. Measuring the real prompt minus its diff removes the guesswork.
    let overheadChars = buildPrompt({
      ...input, diff: '', adversarial, maxPromptTokens: regionBudgetTokens,
    }).length;
    let plan = planJudgeCalls({
      diff: input.diff,
      overheadChars,
      maxPromptTokens: seat.provider.maxPromptTokens,
      maxChunks,
    });

    // A CHUNKED prompt is not a single-pass prompt with a smaller diff: it also carries the
    // "PART i OF n" header, the three-valued verdict menu, and the paragraph explaining that
    // the Tier 1 results are global. Measuring overhead once, in single-pass mode, promises
    // every chunk a fit it cannot deliver — the same class of mistake as budgeting the diff
    // alone. SAFETY_FACTOR happened to absorb it at a 30K budget, which is exactly why it went
    // unnoticed. So once we know the diff must be split, re-plan against the real chunked
    // overhead, sized with the widest part header we could ever print (maxChunks/maxChunks).
    if (!plan.singlePass && plan.chunks.length) {
      const chunkedOverhead = buildPrompt({
        ...input, diff: '', adversarial, maxPromptTokens: regionBudgetTokens,
        chunk: { index: maxChunks, total: maxChunks },
      }).length;
      if (chunkedOverhead > overheadChars) {
        overheadChars = chunkedOverhead;
        plan = planJudgeCalls({
          diff: input.diff,
          overheadChars,
          maxPromptTokens: seat.provider.maxPromptTokens,
          maxChunks,
        });
      }
    }

    if (plan.coverage.overBudget) {
      throw new Error(
        `Judge prompt overhead (${overheadChars} chars) alone exceeds the ${seat.family} budget of ` +
        `${seat.provider.maxPromptTokens} tokens — no room left for any diff. Reduce the number of ` +
        'acceptance criteria, or raise the seat budget if the account\'s rate limit allows it.'
      );
    }

    const results = [];
    for (let i = 0; i < plan.chunks.length; i++) {
      const prompt = buildPrompt({
        ...input,
        diff: plan.chunks[i].text,
        adversarial,
        maxPromptTokens: regionBudgetTokens,
        chunk: { index: i + 1, total: plan.chunks.length },
      });
      // Pace against the seat's per-minute ceiling BEFORE spending, not after failing. Chunks
      // run sequentially on one seat for this reason; separate vendors still run in parallel
      // because they draw on separate quotas.
      if (i > 0) await doSleep(paceMs(estimateTokens(prompt), seat.provider.tpm));
      if (plan.chunks.length > 1) {
        logger.info(`${seat.family} judge: part ${i + 1}/${plan.chunks.length} (${plan.chunks[i].paths.length} file(s))`);
      }
      const parsed = parseSeatResponse(await callOnce(seat, prompt));
      results.push({
        assessment: parsed.assessment || '',
        criteria: Array.isArray(parsed.criteria) ? parsed.criteria : [],
      });
    }

    // Single pass ⇒ the seat's own rulings, unreconciled. Every CONSUMER of a raw seat
    // result projects it onto the spec itself — the jury via mergeJuryResults, the solo
    // judge via alignSingleRulings below — because only the jury can tell the difference
    // between a vendor that ruled "not met" and one that stayed silent, and it needs that
    // difference to name the objector. Projecting here would flatten both into a dissent.
    //
    // Gate on plan.singlePass, NOT chunks.length: a file bigger than the whole budget packs
    // into exactly one TRUNCATED chunk, which also satisfies `length === 1`. That took this
    // return and discarded plan.coverage — half a diff judged, reported as a complete
    // reading. Partial evidence goes through mergeChunkRulings, which prints what it saw.
    if (plan.singlePass) {
      return {
        family: seat.family,
        model: seat.model,
        adversarial,
        assessment: results[0].assessment,
        criteria: results[0].criteria,
      };
    }

    return mergeChunkRulings({
      specCriteria: input.criteria || [],
      chunkResults: results,
      coverage: plan.coverage,
      family: seat.family,
      model: seat.model,
      adversarial,
    });
  };

  // One configured family — the default, and the path that had no merge step at all. The
  // jury reconciles its seats against the spec in mergeJuryResults and a chunked seat
  // reconciles itself in mergeChunkRulings; a lone single-pass seat reconciled against
  // nothing and its raw array went straight to verdict.js, where an empty one meant
  // "nothing unmet" and composed to VERIFIED. alignSingleRulings is that missing step, so
  // all three paths now answer for every criterion in the spec.
  //
  // A chunked result has already been reconciled (and carries `coverage`, which this must
  // not drop), so it passes through untouched.
  if (families.length === 1) {
    return withBench(async function judge(input) {
      const seatResult = await runSeat(active[0], input);
      if (seatResult.chunked) return seatResult;
      return {
        ...seatResult,
        criteria: alignSingleRulings({ specCriteria: input.criteria || [], result: seatResult }),
      };
    });
  }

  // Jury: every seated vendor votes in parallel. A vendor that errors (bad key, rate limit,
  // safety block) or was never keyed is recorded as a failure and the surviving seats still
  // produce a verdict — but flagged DEGRADED, so a jury of one can never quietly masquerade
  // as two-vendor agreement. Only an empty bench is a hard error.
  return withBench(async function jury(input) {
    const settled = await Promise.allSettled(active.map((seat) => runSeat(seat, input)));
    const results = [];
    const failures = seats
      .filter((seat) => !active.some((a) => a.family === seat.family))
      .map((seat) => ({ family: seat.family, error: `${seat.provider.apiKeyEnv} not set` }));

    settled.forEach((s, i) => {
      if (s.status === 'fulfilled') results.push(s.value);
      else failures.push({ family: active[i].family, error: String((s.reason && s.reason.message) || s.reason) });
    });

    if (!results.length) {
      throw new Error(
        `All ${seats.length} jury seat(s) failed: ${failures.map((f) => `${f.family}: ${f.error}`).join('; ')}`
      );
    }
    return mergeJuryResults({ specCriteria: input.criteria || [], results, failures, adversarial });
  });
}

module.exports = {
  createJudge, assertCrossFamily, buildPrompt, alignSingleRulings, mergeJuryResults,
  mergeChunkRulings, chunkVerdict, describeCoverage, PROVIDERS,
};
