/**
 * judge.js — Tier 3 cross-family judge.
 *
 * The code under review is generated by Claude (Anthropic). To avoid a model
 * grading its own family's output, the judge MUST be a different family. This
 * is a load-bearing safety rule: Felix refuses to run with an Anthropic judge.
 *
 * Two judge families are implemented via plain REST (no SDK dependency): OpenAI
 * (default) and Google Gemini — a genuinely different vendor, which is the whole
 * point of a cross-family second opinion (R2b). Select with FELIX_JUDGE_FAMILY.
 * The judge reads the spec criteria + diff + Tier 1 outputs and rules each
 * criterion met/unmet with a short reason.
 */

const { logger } = require('./util/logger');
const { estimateTokens, planJudgeCalls, paceMs, DEFAULT_MAX_CHUNKS } = require('./budget');

const ANTHROPIC_HINTS = [/anthropic/i, /\bclaude\b/i];

// A judge call that 429s on a RATE limit is worth retrying — the quota refills on a timer.
// Bounded, because a PR check that retries forever is worse than one that reports
// INSUFFICIENT EVIDENCE.
const MAX_RATE_LIMIT_RETRIES = 2;
const RETRY_BASE_MS = 20_000;

// …but OpenAI also returns 429 for a request that is too large for the per-minute budget
// FULL STOP ("Request too large for gpt-4.1 … TPM: Limit 30000, Requested 61227"). Waiting
// cannot help: the quota refills to a ceiling the request still exceeds. Retrying that is a
// guaranteed 60-second detour to the same failure, so it is thrown immediately. The budget
// planner should stop us from ever sending one; this is the belt to that suspenders.
const TOO_LARGE = /too large/i;

// Transient server-side failures deserve the same treatment as a rate limit: the vendor is
// telling us to come back, not that the request is wrong. Gemini in particular answers 503
// "This model is currently experiencing high demand … usually temporary" under load, and a
// seat that gives up on the first one silently DEGRADES the jury to a single vendor — which
// is the exact failure mode the two-vendor jury exists to prevent. Observed twice in one day
// on gemini-3.6-flash, both times knocking the jury down to openai-only.
const TRANSIENT_STATUSES = new Set([500, 502, 503, 504]);

const sleep = (ms) => (ms > 0 ? new Promise((r) => setTimeout(r, ms)) : Promise.resolve());

/**
 * Build the error for a non-OK judge response, carrying the HTTP status as a property.
 * The retry path keys off `err.status === 429` rather than grepping the message — a
 * message that happens to contain "429" (an echoed diff, a token count) must not be
 * mistaken for a rate limit.
 */
function httpError(res, bodyText) {
  const err = new Error(`Judge call failed: ${res.status} ${String(bodyText).slice(0, 200)}`);
  err.status = res.status;
  // Vendors send Retry-After on rate limits; honoring it beats guessing a backoff.
  const retryAfter = Number(res.headers && res.headers.get && res.headers.get('retry-after'));
  if (Number.isFinite(retryAfter) && retryAfter > 0) err.retryAfterMs = retryAfter * 1000;
  return err;
}

/** Throws if the configured judge is the same family as the code generator. */
function assertCrossFamily(family, model) {
  const f = String(family || '').toLowerCase();
  const m = String(model || '');
  if (f === 'anthropic' || ANTHROPIC_HINTS.some((re) => re.test(f) || re.test(m))) {
    throw new Error(
      `Cross-family integrity violation: judge family/model "${family}/${model}" is Anthropic. ` +
      'Felix refuses to let the code generator grade its own output. Set FELIX_JUDGE_FAMILY/MODEL to a different family (e.g. openai/gpt-4.1).'
    );
  }
}

/**
 * @param {{index:number,total:number}} [chunk] Set when the diff was too large for one
 *   call and is being judged in several passes. A judge seeing only PART of a diff must
 *   NOT report "not met" for something it simply cannot see — that false negative is
 *   indistinguishable from a real finding. So chunked mode swaps the boolean `met` for a
 *   three-valued verdict and mergeChunkRulings reassembles it (see there for why the two
 *   directions merge differently).
 */
function buildPrompt({ prTitle, criteria, diff, tier1, adversarial = false, chunk = null }) {
  const criteriaList = criteria.map((c, i) => `${i + 1}. ${c.text}`).join('\n');
  const checks = tier1
    .map((c) => `- ${c.name}: ${c.status.toUpperCase()} (${c.detail})`)
    .join('\n');
  const tier1Output = tier1
    .filter((c) => c.status === 'fail' && c.output)
    .map((c) => `### ${c.name} output\n${c.output}`)
    .join('\n\n');

  // No truncation here any more. The caller (runSeat) sizes the diff against the seat's
  // rate limit before we ever get here, and splits it if it doesn't fit — so whatever
  // arrives is already known to be within budget.
  const diffText = String(diff || '');
  const chunked = Boolean(chunk && chunk.total > 1);

  // Two grading modes. Adversarial "refute-first" forces the judge to state the strongest
  // reason each criterion is NOT met BEFORE deciding — the commit-then-grade technique that
  // sharply cuts over-eager "met" (false-positive) verdicts. Opt-in; default keeps the plain
  // prompt so existing behavior is unchanged until a repo turns it on.
  const instructions = adversarial ? [
    'You are a SKEPTICAL independent verification judge. You did NOT write this code. Your job is',
    'to catch PRs that only APPEAR to satisfy their acceptance criteria.',
    'For EACH criterion, work strictly in this order:',
    '  1. REFUTE — write the single strongest CONCRETE reason the submitted code does NOT satisfy',
    '     the criterion: a missing case, an unhandled path, a mock hiding real behavior, an',
    '     unimplemented branch. Ground it in the actual diff + test evidence, not speculation.',
    '  2. DECIDE — mark met:true ONLY if that refutation clearly fails against the diff + test',
    '     evidence. If the refutation stands, or the evidence is ambiguous or absent, mark met:false.',
    'Judge behavior and evidence, not intentions. The diff includes the full added source for new',
    'files, so an implementation present in the diff counts as shown. When unsure, prefer met:false.',
  ] : [
    'You are an independent verification judge. You did NOT write this code.',
    'Decide, for each acceptance criterion, whether the SUBMITTED CODE actually satisfies it.',
    'Judge behavior and evidence — not intentions. If the diff plus test results do not',
    'clearly demonstrate a criterion is met, mark it not met. Note: the diff includes the',
    'full added source for new files, so an implementation present in the diff counts as shown.',
  ];

  // In chunked mode the ONLY change to the grading rules is that "I can't see it here" gets
  // its own answer, distinct from "I looked and it's wrong". Everything else — including the
  // adversarial refute-first discipline above — is untouched.
  //
  // The "WHAT IS SPLIT" paragraph is load-bearing, not decoration. Without it every option
  // below reads as "…this part…", so a judge asked whether the build passes correctly answers
  // that a SLICE OF A DIFF cannot show that — in all N parts — and mergeChunkRulings sees
  // all-not_shown ⇒ NOT met. That is what happened on a large real PR: `build/smoke — exit 0` was
  // sitting in all 4 prompts and every part still answered not_shown. Only the DIFF is split;
  // the checks ran once over the whole PR and appear whole in every part.
  const chunkInstructions = chunked ? [
    '',
    `IMPORTANT: you are being shown PART ${chunk.index} OF ${chunk.total} of a large diff.`,
    'The files in this part are complete, but other parts contain other files you cannot see.',
    'WHAT IS SPLIT: only the UNIFIED DIFF. The DETERMINISTIC CHECK RESULTS (Tier 1) section is',
    'GLOBAL — those commands ran once against the WHOLE pull request, and you are seeing their',
    'complete results, identical in every part. So for a criterion about the OUTCOME OF A CHECK',
    '(e.g. "`npm run build` exits 0", "the test suite passes", "lint is clean"), decide it from',
    'that result and answer "met" or "violated" in EVERY part — NEVER "not_shown". That evidence',
    'is not split and is fully in front of you. This does not make a green check evidence for',
    'criteria about code: a passing build says nothing about whether a feature was implemented.',
    'For each criterion answer with exactly one verdict:',
    '  "met"       — this part of the diff, or the global check results, shows the criterion IS satisfied.',
    '  "violated"  — this part of the diff, or the global check results, shows it is NOT satisfied.',
    '  "not_shown" — neither this part nor the check results bears on the criterion either way.',
    'Use "not_shown" freely for criteria about code. Do NOT answer "violated" merely because the',
    'relevant code is absent from this part — absence here is expected and is what "not_shown" means.',
  ] : [];

  const responseFormat = chunked
    ? (adversarial
      ? '{"assessment":"<2-3 sentence summary of THIS part>","criteria":[{"text":"<criterion>","refutation":"<strongest reason it is NOT met, or empty if not_shown>","verdict":"met"|"violated"|"not_shown","reason":"<short>"}]}'
      : '{"assessment":"<2-3 sentence summary of THIS part>","criteria":[{"text":"<criterion>","verdict":"met"|"violated"|"not_shown","reason":"<short>"}]}')
    : (adversarial
      ? '{"assessment":"<2-3 sentence summary>","criteria":[{"text":"<criterion>","refutation":"<strongest reason it is NOT met>","met":true|false,"reason":"<why the refutation does or does not hold>"}]}'
      : '{"assessment":"<2-3 sentence summary>","criteria":[{"text":"<criterion>","met":true|false,"reason":"<short>"}]}');

  return [
    ...instructions,
    ...chunkInstructions,
    '',
    `PR title: ${prTitle}`,
    '',
    'ACCEPTANCE CRITERIA:',
    criteriaList || '(none provided)',
    '',
    'DETERMINISTIC CHECK RESULTS (Tier 1):',
    checks || '(none)',
    tier1Output ? `\nFAILING CHECK OUTPUT:\n${tier1Output}` : '',
    '',
    chunked ? `UNIFIED DIFF (part ${chunk.index} of ${chunk.total}):` : 'UNIFIED DIFF:',
    '```diff',
    diffText,
    '```',
    '',
    'Respond with ONLY JSON of the form:',
    responseFormat,
  ].join('\n');
}

/**
 * Judge provider registry. Each family is a genuinely different vendor (the point of a
 * cross-family second opinion) and speaks plain REST — no SDK dependency. A provider's
 * `call` builds the vendor-specific request and returns the model's RAW text (a JSON
 * string); the shared parser in createJudge turns that into the common verdict shape, so
 * both families are held to the identical output schema from buildPrompt.
 *
 *   defaultModel — used when FELIX_JUDGE_MODEL is unset (per-family, so a Gemini run never
 *                  inherits the OpenAI default).
 *   apiKeyEnv    — the env var holding that vendor's key; missing key ⇒ judge skipped.
 *   call         — async ({ apiKey, model, prompt, fetch }) → raw JSON string (or throws).
 */
const PROVIDERS = {
  openai: {
    defaultModel: 'gpt-4.1',
    apiKeyEnv: 'OPENAI_API_KEY',
    // Sized against a measured gpt-4.1 TPM ceiling of 30,000 — the number in the
    // live 429, not a guess. NOT the context window: gpt-4.1's window is ~1M tokens, and
    // budgeting against that is precisely the bug this replaced.
    tpm: 30_000,
    maxPromptTokens: 30_000,
    async call({ apiKey, model, prompt, fetch }) {
      const res = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model,
          temperature: 0,
          response_format: { type: 'json_object' },
          messages: [{ role: 'user', content: prompt }],
        }),
      });
      if (!res.ok) {
        const txt = await res.text();
        throw httpError(res, txt);
      }
      const data = await res.json();
      const text = data.choices?.[0]?.message?.content;
      if (!text) throw new Error('Judge returned an empty response (no choices/content).');
      return text;
    },
  },
  gemini: {
    // NOT gemini-2.5-flash. It's still listed as "stable" in Google's model docs, but the API
    // rejects it for keys created recently: 404 "no longer available to new users". Felix's own
    // production run caught this live — the two-vendor jury silently ran DEGRADED (openai-only) on
    // every PR, which is the one thing the jury exists to prevent. Verified against the official
    // model list (ai.google.dev/gemini-api/docs/models), not a comparison blog.
    defaultModel: 'gemini-3.6-flash',
    apiKeyEnv: 'GEMINI_API_KEY',
    // A paid Gemini key has a far larger per-minute allowance than the OpenAI seat, so the
    // budget is PER VENDOR: Gemini usually judges a big PR in one pass while OpenAI chunks
    // the same diff. Kept well below the advertised ceiling — the cost of being wrong here
    // is a 429, and the point of this module is to stop guessing high.
    tpm: 200_000,
    maxPromptTokens: 200_000,
    async call({ apiKey, model, prompt, fetch }) {
      // Key travels in the x-goog-api-key HEADER, never the URL query string — so it can't
      // leak through request logs, proxies, or referrers. (Gemini accepts ?key= too; we
      // deliberately don't use it.)
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;
      const res = await fetch(url, {
        method: 'POST',
        headers: {
          'x-goog-api-key': apiKey,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{ role: 'user', parts: [{ text: prompt }] }],
          // responseMimeType forces raw JSON (no ```json fences) so the shared parser below
          // works identically to OpenAI's json_object mode.
          generationConfig: { temperature: 0, responseMimeType: 'application/json' },
        }),
      });
      if (!res.ok) {
        const txt = await res.text();
        throw httpError(res, txt);
      }
      const data = await res.json();
      const cand = data.candidates?.[0];
      // Join all text parts (Gemini may split output). Empty ⇒ the response was blocked or hit
      // a non-STOP finish (SAFETY / MAX_TOKENS); surface WHY instead of a cryptic parse error.
      const text = (cand?.content?.parts || []).map((p) => p && p.text).filter(Boolean).join('');
      if (!text) {
        const why = cand?.finishReason || data.promptFeedback?.blockReason || 'no candidates';
        throw new Error(`Judge returned no content (Gemini finishReason=${why}).`);
      }
      return text;
    },
  },
};

/** Split a comma-separated env list into trimmed, non-empty entries. */
function parseList(value, { lower = false } = {}) {
  return String(value || '')
    .split(',')
    .map((s) => (lower ? s.trim().toLowerCase() : s.trim()))
    .filter(Boolean);
}

const normText = (s) => String(s || '').trim().toLowerCase().replace(/\s+/g, ' ');

/**
 * Find one judge's ruling on a given spec criterion. Judges are prompted with the criteria
 * in order and asked to echo the text back, but wording drifts — so match on normalized
 * text first and fall back to position. A criterion a judge never ruled on returns null,
 * which the merge treats as NOT met: silence is never taken as a pass.
 */
function findRuling(result, criterionText, index) {
  const list = Array.isArray(result.criteria) ? result.criteria : [];
  const target = normText(criterionText);
  return list.find((c) => normText(c.text) === target) || list[index] || null;
}

/**
 * Read one chunk's answer for a criterion as met | violated | not_shown.
 *
 * Chunked prompts ask for a three-valued `verdict` string, but a model can ignore the
 * schema and send the boolean `met` from the single-pass format. The fallback maps
 * met:false to "not_shown", NOT to "violated" — deliberately. A chunk that simply doesn't
 * contain the relevant file will say "not met", and promoting that to a violation would
 * recreate the exact false-negative this whole change exists to remove. Nothing is lost by
 * being lenient here: if EVERY chunk comes back not_shown the criterion still fails (see
 * mergeChunkRulings), so the fallback can never manufacture a pass.
 */
function chunkVerdict(ruling) {
  if (!ruling) return null;
  const v = String(ruling.verdict || '').trim().toLowerCase();
  if (v === 'met' || v === 'violated' || v === 'not_shown') return v;
  if (ruling.met === true) return 'met';
  if (ruling.met === false) return 'not_shown';
  return null;
}

/**
 * alignSingleRulings — project ONE seat's single-pass rulings onto the spec's criteria.
 *
 * The third member of the merge family, and the one that was missing. Its two siblings
 * below both build their answer by mapping over specCriteria, so a criterion the model
 * never addressed comes back not-met. The single-pass path returned the model's own array
 * verbatim instead — so an empty, truncated or malformed response contained nothing marked
 * met:false, and verdict.js read "nothing unmet" as VERIFIED. Single seat + single call is
 * the DEFAULT configuration, which meant the setup almost everyone runs had the weakest
 * rule in the codebase.
 *
 * Same invariant as its siblings, stated once more because it is the whole product: the
 * result has exactly one entry per SPEC criterion, `met` is true only where the judge said
 * so explicitly, and silence is not a pass. `met !== true` rather than `met === false` on
 * purpose — a model that sends the string "false", or omits the field on a truncated
 * completion, has not confirmed anything.
 */
function alignSingleRulings({ specCriteria = [], result }) {
  return specCriteria.map((sc, i) => {
    const ruling = findRuling(result, sc.text, i);
    if (!ruling) {
      return { text: sc.text, met: false, reason: 'The judge returned no ruling on this criterion.' };
    }
    if (ruling.met !== true) {
      return { text: sc.text, met: false, reason: ruling.reason || '(no reason given)' };
    }
    return { text: sc.text, met: true, reason: ruling.reason || 'met' };
  });
}

/**
 * mergeChunkRulings — reassemble one seat's verdict from several passes over a split diff.
 *
 * This merges in the OPPOSITE direction from the jury merge below, and the asymmetry is
 * deliberate:
 *
 *   • Across VENDORS (mergeJuryResults) the merge is AND. Two vendors are two independent
 *     opinions on the same evidence, so agreement must be earned.
 *   • Across CHUNKS (here) the merge is closer to OR. The chunks are not independent
 *     opinions — they are disjoint slices of ONE body of evidence. Requiring every slice to
 *     confirm a criterion would fail every criterion whose implementation lives in a single
 *     file, which is most of them.
 *
 * Precedence is violated > met > all-not_shown:
 *   - a concrete violation anywhere beats confirmation elsewhere (a universal criterion like
 *     "no secrets are logged" must not pass because four of five slices looked clean);
 *   - otherwise positive evidence in any slice carries it (an existential criterion like
 *     "adds a retry helper" is satisfied by the one slice containing the helper);
 *   - if no slice showed anything, the criterion is NOT met — silence is never a pass, the
 *     same rule the jury merge applies to a silent vendor.
 */
function mergeChunkRulings({ specCriteria = [], chunkResults, coverage, family, model, adversarial = false }) {
  const criteria = specCriteria.map((sc, i) => {
    const rulings = chunkResults.map((r, ci) => ({
      part: ci + 1,
      ruling: findRuling(r, sc.text, i),
      verdict: chunkVerdict(findRuling(r, sc.text, i)),
    }));

    const violated = rulings.filter((v) => v.verdict === 'violated');
    const affirmed = rulings.filter((v) => v.verdict === 'met');

    if (violated.length) {
      const v = violated[0];
      return {
        text: sc.text, met: false,
        reason: `Part ${v.part} of ${chunkResults.length} found a violation: ${v.ruling.reason || '(no reason given)'}`,
      };
    }
    if (affirmed.length) {
      const a = affirmed[0];
      return {
        text: sc.text, met: true,
        reason: `${a.ruling.reason || 'met'} (evidence in part ${a.part} of ${chunkResults.length})`,
      };
    }
    return {
      text: sc.text, met: false,
      reason: `No part of the diff showed evidence for this criterion (judged in ${chunkResults.length} parts).`,
    };
  });

  return {
    family, model, adversarial,
    chunked: true,
    coverage,
    assessment: [describeCoverage(coverage), ...chunkResults.map((r, i) => `- part ${i + 1}: ${r.assessment || '(no assessment)'}`)].join('\n'),
    criteria,
  };
}

/** One-line, honest statement of how much of the diff the judge actually saw. */
function describeCoverage(coverage) {
  const pct = coverage.totalChars
    ? Math.round((coverage.judgedChars / coverage.totalChars) * 100)
    : 100;
  const parts = [`Diff too large for one call — judged in ${coverage.chunkCount} parts covering ~${pct}% of the diff`];
  if (coverage.omittedPaths.length) {
    parts.push(`PARTIAL: ${coverage.omittedPaths.length} file(s) not judged (${coverage.omittedPaths.slice(0, 5).join(', ')}${coverage.omittedPaths.length > 5 ? ', …' : ''})`);
  }
  if (coverage.truncatedPaths.length) {
    parts.push(`truncated: ${coverage.truncatedPaths.join(', ')}`);
  }
  return `${parts.join('. ')}.`;
}

/**
 * mergeJuryResults — conservative unanimity merge (R2b slice 2).
 *
 * A criterion counts as met ONLY if EVERY seated judge rules it met. One dissent — or one
 * judge that never ruled on it — blocks. That asymmetry is the entire point: the jury
 * exists to kill false "VERIFIED" verdicts, so agreement must be earned while disagreement
 * is cheap. The split is named in the reason so a human can see WHICH vendor objected and
 * why, rather than getting an unexplained downgrade.
 */
function mergeJuryResults({ specCriteria = [], results, failures = [], adversarial = false }) {
  const voters = results.map((r) => r.family);
  let splits = 0;

  const criteria = specCriteria.map((sc, i) => {
    const rulings = results.map((r) => ({ family: r.family, ruling: findRuling(r, sc.text, i) }));
    const silent = rulings.filter((v) => !v.ruling);
    const dissent = rulings.filter((v) => v.ruling && v.ruling.met !== true);
    const met = rulings.length > 0 && silent.length === 0 && dissent.length === 0;
    if (!met) splits += 1;

    let reason;
    if (met) {
      reason = `${rulings[0].ruling.reason || 'met'} (unanimous: ${voters.join(' + ')})`;
    } else {
      const parts = [
        ...dissent.map((d) => `${d.family} says NOT met: ${d.ruling.reason || '(no reason given)'}`),
        ...silent.map((s) => `${s.family} returned no ruling on this criterion`),
      ];
      const agreed = rulings.filter((v) => v.ruling && v.ruling.met === true).map((v) => v.family);
      if (agreed.length) parts.push(`${agreed.join(' + ')} say met`);
      reason = `Split verdict — ${parts.join('; ')}.`;
    }
    return { text: sc.text, met, reason };
  });

  const degraded = failures.length > 0;
  const header = [
    `${results.length}-vendor jury (${voters.join(' + ')}), unanimity required`,
    degraded ? `DEGRADED — ${failures.map((f) => `${f.family} unavailable: ${f.error}`).join('; ')}` : null,
    `${splits} of ${criteria.length} criteria split or unmet`,
  ].filter(Boolean).join('. ');

  return {
    family: voters.join('+'),
    model: results.map((r) => r.model).join('+'),
    adversarial,
    // Per-vendor detail is preserved so the log/comment can show who said what.
    jury: results.map((r) => ({
      family: r.family, model: r.model, assessment: r.assessment, criteria: r.criteria,
    })),
    degraded,
    failures,
    splits,
    assessment: [`${header}.`, ...results.map((r) => `- ${r.family}: ${r.assessment || '(no assessment)'}`)].join('\n'),
    criteria,
  };
}

/**
 * @param {object} env
 * @param {{adversarial?: boolean, fetchImpl?: Function}} opts
 *   adversarial=true uses the refute-first prompt (R2a). fetchImpl injects a fetch for
 *   offline tests (defaults to the global fetch).
 *
 * FELIX_JUDGE_FAMILY accepts ONE family ("gemini") or a comma-separated JURY
 * ("openai,gemini"). A jury runs every seated vendor in parallel and merges by unanimity,
 * so two independent vendors must both agree before a criterion counts as met — which is
 * what kills single-model flukes. Duplicate families collapse: the same vendor voting
 * twice is not an independent second opinion.
 *
 * @returns judge fn, or null if NO seated family has an API key (judge skipped →
 *   INSUFFICIENT EVIDENCE).
 */
function createJudge(env = process.env, { adversarial = false, fetchImpl, sleepImpl } = {}) {
  const doFetch = fetchImpl || fetch;
  // Injectable so the offline suite can exercise pacing and retry logic without actually
  // waiting out a rate-limit window.
  const doSleep = sleepImpl || sleep;
  // Escape hatch for a repo whose PRs are routinely enormous and who would rather spend the
  // CI minutes than accept partial coverage.
  const maxChunks = Number(env.FELIX_JUDGE_MAX_CHUNKS) > 0
    ? Number(env.FELIX_JUDGE_MAX_CHUNKS)
    : DEFAULT_MAX_CHUNKS;
  const requested = parseList(env.FELIX_JUDGE_FAMILY || 'openai', { lower: true });
  const families = [...new Set(requested.length ? requested : ['openai'])];
  const models = parseList(env.FELIX_JUDGE_MODEL);

  // A single model override cannot describe a multi-vendor jury (a gpt-* id is meaningless
  // to Gemini). Demand one model per family, or none at all — never guess a mapping.
  if (models.length > 1 && models.length !== families.length) {
    throw new Error(
      `FELIX_JUDGE_MODEL lists ${models.length} model(s) but FELIX_JUDGE_FAMILY seats ${families.length} judge(s). ` +
      "Provide one model per family in the same order, or leave it unset to use each family's default."
    );
  }
  if (models.length === 1 && families.length > 1) {
    throw new Error(
      `FELIX_JUDGE_MODEL="${models[0]}" is ambiguous for a ${families.length}-vendor jury. ` +
      "Provide one model per family in the same order, or leave it unset to use each family's default."
    );
  }

  const budgetOverride = Number(env.FELIX_JUDGE_MAX_PROMPT_TOKENS) > 0
    ? Number(env.FELIX_JUDGE_MAX_PROMPT_TOKENS)
    : null;

  const seats = families.map((family, i) => {
    const rawProvider = PROVIDERS[family];
    const model = models[i] || (rawProvider && rawProvider.defaultModel) || '';
    // Load-bearing safety guard, applied PER SEAT: the code under review is Claude's, so
    // every judge must be a different family. Runs before the "known family?" check so a
    // misconfigured Anthropic judge always fails with the integrity error.
    assertCrossFamily(family, model);
    if (!rawProvider) {
      throw new Error(
        `FELIX_JUDGE_FAMILY="${family}" is not supported. Available families: ${Object.keys(PROVIDERS).join(', ')}.`
      );
    }
    // A repo on a higher (or lower) rate-limit tier can override the per-seat budget rather
    // than editing the registry. Applies to every seat: it describes THIS ACCOUNT's ceiling,
    // which is a property of the billing plan, not of the vendor.
    const provider = budgetOverride
      ? { ...rawProvider, maxPromptTokens: budgetOverride, tpm: budgetOverride }
      : rawProvider;
    return { family, provider, model };
  });

  const active = [];
  for (const seat of seats) {
    const apiKey = env[seat.provider.apiKeyEnv];
    if (!apiKey) {
      logger.warn(`${seat.provider.apiKeyEnv} not set — ${seat.family} judge seat skipped.`);
      continue;
    }
    active.push({ ...seat, apiKey });
  }
  if (!active.length) return null;

  // One call, with a bounded retry when the vendor says "come back later" rather than "your
  // request is wrong". Rate limits and transient 5xx both clear on their own; everything
  // else — a bad key, a safety block, an over-sized request — is final and fails fast.
  const callOnce = async (seat, prompt) => {
    for (let attempt = 0; ; attempt++) {
      try {
        return await seat.provider.call({ apiKey: seat.apiKey, model: seat.model, prompt, fetch: doFetch });
      } catch (e) {
        // A 429 clears when the quota refills; a 5xx clears when the vendor recovers. Both are
        // worth waiting on. "Request too large" is neither — see TOO_LARGE.
        const rateLimited = e.status === 429 && !TOO_LARGE.test(e.message);
        const retryable = rateLimited || TRANSIENT_STATUSES.has(e.status);
        if (!retryable || attempt >= MAX_RATE_LIMIT_RETRIES) throw e;
        const waitMs = e.retryAfterMs || RETRY_BASE_MS * (attempt + 1);
        logger.warn(`${seat.family} judge rate-limited — retrying in ${Math.round(waitMs / 1000)}s (attempt ${attempt + 1}/${MAX_RATE_LIMIT_RETRIES}).`);
        await doSleep(waitMs);
      }
    }
  };

  const parseSeatResponse = (raw) => {
    try {
      return JSON.parse(raw);
    } catch (e) {
      throw new Error(`Judge returned non-JSON: ${e.message}`);
    }
  };

  const runSeat = async (seat, input) => {
    // Budget the WHOLE prompt, not just the diff. The original bug sized a 240 KB diff cap
    // against a 60K-token estimate and ignored the instructions, criteria and Tier 1 output
    // riding along with it — the live 429 billed 61,227 tokens for a request the cap thought
    // was exactly at budget. Measuring the real prompt minus its diff removes the guesswork.
    let overheadChars = buildPrompt({ ...input, diff: '', adversarial }).length;
    let plan = planJudgeCalls({
      diff: input.diff,
      overheadChars,
      maxPromptTokens: seat.provider.maxPromptTokens,
      maxChunks,
    });

    // A CHUNKED prompt is not a single-pass prompt with a smaller diff: it also carries the
    // "PART i OF n" header, the three-valued verdict menu, and the paragraph explaining that
    // the Tier 1 results are global. Measuring overhead once, in single-pass mode, promises
    // every chunk a fit it cannot deliver — the same class of mistake as budgeting the diff
    // alone. SAFETY_FACTOR happened to absorb it at a 30K budget, which is exactly why it went
    // unnoticed. So once we know the diff must be split, re-plan against the real chunked
    // overhead, sized with the widest part header we could ever print (maxChunks/maxChunks).
    if (!plan.singlePass && plan.chunks.length) {
      const chunkedOverhead = buildPrompt({
        ...input, diff: '', adversarial, chunk: { index: maxChunks, total: maxChunks },
      }).length;
      if (chunkedOverhead > overheadChars) {
        overheadChars = chunkedOverhead;
        plan = planJudgeCalls({
          diff: input.diff,
          overheadChars,
          maxPromptTokens: seat.provider.maxPromptTokens,
          maxChunks,
        });
      }
    }

    if (plan.coverage.overBudget) {
      throw new Error(
        `Judge prompt overhead (${overheadChars} chars) alone exceeds the ${seat.family} budget of ` +
        `${seat.provider.maxPromptTokens} tokens — no room left for any diff. Reduce the number of ` +
        'acceptance criteria, or raise the seat budget if the account\'s rate limit allows it.'
      );
    }

    const results = [];
    for (let i = 0; i < plan.chunks.length; i++) {
      const prompt = buildPrompt({
        ...input,
        diff: plan.chunks[i].text,
        adversarial,
        chunk: { index: i + 1, total: plan.chunks.length },
      });
      // Pace against the seat's per-minute ceiling BEFORE spending, not after failing. Chunks
      // run sequentially on one seat for this reason; separate vendors still run in parallel
      // because they draw on separate quotas.
      if (i > 0) await doSleep(paceMs(estimateTokens(prompt), seat.provider.tpm));
      if (plan.chunks.length > 1) {
        logger.info(`${seat.family} judge: part ${i + 1}/${plan.chunks.length} (${plan.chunks[i].paths.length} file(s))`);
      }
      const parsed = parseSeatResponse(await callOnce(seat, prompt));
      results.push({
        assessment: parsed.assessment || '',
        criteria: Array.isArray(parsed.criteria) ? parsed.criteria : [],
      });
    }

    // Single pass ⇒ the seat's own rulings, unreconciled. Every CONSUMER of a raw seat
    // result projects it onto the spec itself — the jury via mergeJuryResults, the solo
    // judge via alignSingleRulings below — because only the jury can tell the difference
    // between a vendor that ruled "not met" and one that stayed silent, and it needs that
    // difference to name the objector. Projecting here would flatten both into a dissent.
    //
    // Gate on plan.singlePass, NOT chunks.length: a file bigger than the whole budget packs
    // into exactly one TRUNCATED chunk, which also satisfies `length === 1`. That took this
    // return and discarded plan.coverage — half a diff judged, reported as a complete
    // reading. Partial evidence goes through mergeChunkRulings, which prints what it saw.
    if (plan.singlePass) {
      return {
        family: seat.family,
        model: seat.model,
        adversarial,
        assessment: results[0].assessment,
        criteria: results[0].criteria,
      };
    }

    return mergeChunkRulings({
      specCriteria: input.criteria || [],
      chunkResults: results,
      coverage: plan.coverage,
      family: seat.family,
      model: seat.model,
      adversarial,
    });
  };

  // One configured family — the default, and the path that had no merge step at all. The
  // jury reconciles its seats against the spec in mergeJuryResults and a chunked seat
  // reconciles itself in mergeChunkRulings; a lone single-pass seat reconciled against
  // nothing and its raw array went straight to verdict.js, where an empty one meant
  // "nothing unmet" and composed to VERIFIED. alignSingleRulings is that missing step, so
  // all three paths now answer for every criterion in the spec.
  //
  // A chunked result has already been reconciled (and carries `coverage`, which this must
  // not drop), so it passes through untouched.
  if (families.length === 1) {
    return async function judge(input) {
      const seatResult = await runSeat(active[0], input);
      if (seatResult.chunked) return seatResult;
      return {
        ...seatResult,
        criteria: alignSingleRulings({ specCriteria: input.criteria || [], result: seatResult }),
      };
    };
  }

  // Jury: every seated vendor votes in parallel. A vendor that errors (bad key, rate limit,
  // safety block) or was never keyed is recorded as a failure and the surviving seats still
  // produce a verdict — but flagged DEGRADED, so a jury of one can never quietly masquerade
  // as two-vendor agreement. Only an empty bench is a hard error.
  return async function jury(input) {
    const settled = await Promise.allSettled(active.map((seat) => runSeat(seat, input)));
    const results = [];
    const failures = seats
      .filter((seat) => !active.some((a) => a.family === seat.family))
      .map((seat) => ({ family: seat.family, error: `${seat.provider.apiKeyEnv} not set` }));

    settled.forEach((s, i) => {
      if (s.status === 'fulfilled') results.push(s.value);
      else failures.push({ family: active[i].family, error: String((s.reason && s.reason.message) || s.reason) });
    });

    if (!results.length) {
      throw new Error(
        `All ${seats.length} jury seat(s) failed: ${failures.map((f) => `${f.family}: ${f.error}`).join('; ')}`
      );
    }
    return mergeJuryResults({ specCriteria: input.criteria || [], results, failures, adversarial });
  };
}

module.exports = {
  createJudge, assertCrossFamily, buildPrompt, alignSingleRulings, mergeJuryResults,
  mergeChunkRulings, chunkVerdict, describeCoverage, PROVIDERS,
};
